### PR TITLE
Fix Docker builds for `linux/arm/v7`

### PR DESCRIPTION
**Pull request by mchangrh**

### CODE REVIEW

**Comment by CollinHeist** [comment]
Hey want to rebase this to the `web-ui` branch? This branch is for the non-UI

**Comment by mchangrh** [comment]
will rebase manually

**Comment by CollinHeist** [comment]
Thanks! I tested this and still get build errors for that architecture. Any ideas?

**Comment by mchangrh** [comment]
ah, armv7. I tested on arm64. I'll have a go in my own repo

**Comment by mchangrh** [comment]
- add `/root/.cache` caching for python (don't completely rebuilt when dependencies change)
- segment caching to better cache individual python requirement updates
- add all build dependencies for the biggest compiled packages

**Comment by CollinHeist** [comment]
This looks good, thanks a lot for doing it. One question - I see you made a new `Dockerfile.armv7`, but I don't see where that Dockerfile is being used? I would assume it'd be in the workflow, but I don't see that file called out in the build step.

**Comment by mchangrh** [comment]
Nice catch, added the file line and rebased to upstream

**Comment by CollinHeist** [comment]
This looks great - thanks again!

**Pull request merged**
